compiler:
  solc:
    remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.1'
dependencies:
- OpenZeppelin/openzeppelin-contracts@4.9.1
dotenv: .env
networks:
  development:
    verify: false
  ganache-local:
    verify: false
  mainnet-fork:
    verify: false
  sepolia:
    verify: true
wallets:
  key_playground: ${PRIVATE_KEY_PLAYGROUND}
